anguage: php
php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y php5-xsl
  - echo "extension=xsl.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
before_script:
  - composer self-update
  - composer install --dev
script: utilities/phpunit.sh