language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - nightly
  - hhvm
  - hhvm-nightly
install:
  - composer install
script: utilities/phpunit.sh
after_script:
  - cat test/logs/testdox.txt
  - cat test/logs/logfile.tap
  - cat test/logs/logfile.json
  - cat test/logs/coverage.xml
