language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - nightly
  - hhvm
  - hhvm-nightly
matrix:
    allow_failures:
        - php: hhvm
before_script:
  - composer self-update
  - composer install --dev
script: utilities/phpunit.sh